export const PERFUMES = [
  {
    id: 1,
    name: "Midnight Bloom",
    price: 89,
    description: "A mysterious blend of dark florals and warm spices",
    notes: ["Rose", "Oud", "Amber"],
    scentProfile: "Floral & Woody",
    longevity: "8-10 hours",
    season: "Evening",
    recommendation: "Perfect for romantic evenings and special occasions",
  },
  {
    id: 2,
    name: "Velvet Noir",
    price: 95,
    description: "Sophisticated and sensual with warmer undertones",
    notes: ["Jasmine", "Sandalwood", "Musk"],
    scentProfile: "Oriental & Woody",
    longevity: "10-12 hours",
    season: "Evening",
    recommendation: "Ideal for those who love deep, luxurious scents",
  },
  {
    id: 3,
    name: "Citrus Dawn",
    price: 75,
    description: "Fresh and energizing morning fragrance",
    notes: ["Bergamot", "Lemon", "Green Tea"],
    scentProfile: "Citrus & Fresh",
    longevity: "6-8 hours",
    season: "Day",
    recommendation: "Great for daily wear and professional settings",
  },
  {
    id: 4,
    name: "Ocean Breeze",
    price: 79,
    description: "Crisp aquatic notes with a hint of sea salt",
    notes: ["Sea Salt", "Aquatic", "Driftwood"],
    scentProfile: "Aquatic & Fresh",
    longevity: "6-8 hours",
    season: "Day",
    recommendation: "Perfect for summer and casual outings",
  },
  {
    id: 5,
    name: "Amber Sunset",
    price: 85,
    description: "Warm and comforting with golden amber notes",
    notes: ["Amber", "Vanilla", "Cinnamon"],
    scentProfile: "Amber & Warm",
    longevity: "8-10 hours",
    season: "Evening",
    recommendation: "Cozy and inviting for autumn and winter",
  },
  {
    id: 6,
    name: "Floral Paradise",
    price: 82,
    description: "A bouquet of exotic flowers and tropical fruits",
    notes: ["Orchid", "Mango", "Coconut"],
    scentProfile: "Floral & Fruity",
    longevity: "7-9 hours",
    season: "Day",
    recommendation: "Vibrant and joyful for everyday wear",
  },
  {
    id: 7,
    name: "Spice Market",
    price: 88,
    description: "Exotic spices blended with precious woods",
    notes: ["Cardamom", "Clove", "Cedarwood"],
    scentProfile: "Spicy & Woody",
    longevity: "9-11 hours",
    season: "Evening",
    recommendation: "Bold and distinctive for confident wearers",
  },
  {
    id: 8,
    name: "Lavender Dreams",
    price: 72,
    description: "Calming lavender with soft herbal notes",
    notes: ["Lavender", "Chamomile", "Bergamot"],
    scentProfile: "Herbal & Fresh",
    longevity: "6-8 hours",
    season: "Day",
    recommendation: "Soothing and versatile for any time",
  },
  {
    id: 9,
    name: "Rose Garden",
    price: 86,
    description: "Classic rose with modern twist",
    notes: ["Rose", "Peony", "Musk"],
    scentProfile: "Floral & Romantic",
    longevity: "8-10 hours",
    season: "Day",
    recommendation: "Timeless elegance for all occasions",
  },
]

export const CHATBOT_RESPONSES: Record<string, string> = {
  order: 'You can track your order in the "Delivery" section. Just enter your order number to see real-time updates!',
  delivery:
    "We offer fast shipping! Most orders arrive within 3-5 business days. Premium members get free overnight shipping.",
  return:
    "We offer a 30-day return policy. If you're not satisfied with your fragrance, simply return it for a full refund.",
  best: "That depends on your preferences! Are you looking for something fresh and citrusy, warm and cozy, or bold and spicy? Tell me more!",
  evening:
    "For evening wear, I'd recommend Midnight Bloom, Velvet Noir, or Spice Market - they have great longevity and presence.",
  day: "For daytime, try Citrus Dawn, Ocean Breeze, or Lavender Dreams - they're fresh and won't overpower.",
  price: "Our fragrances range from $72 to $95. We have options for every budget!",
  recommendation:
    "Based on your preferences, I'd suggest trying our scent quiz or browsing by scent profile. What type of scent appeals to you?",
  payment: "We accept all major credit cards, PayPal, and Apple Pay. All transactions are secure and encrypted.",
  help: "I can help you find fragrances, track orders, answer questions about our products, and more. What would you like to know?",
  quiz: "Take our scent quiz to discover fragrances perfectly matched to your personality and preferences!",
  floral:
    "Our floral fragrances include Midnight Bloom, Floral Paradise, and Rose Garden. Each offers a unique take on florals!",
  citrus: "For fresh citrus scents, try Citrus Dawn or Ocean Breeze - both are perfect for daytime wear.",
  warm: "Looking for warmth? Amber Sunset and Spice Market are cozy and inviting fragrances.",
  fresh: "Our fresh fragrances include Citrus Dawn, Ocean Breeze, and Lavender Dreams - all perfect for daily wear.",
}
